### ISSUE TITLE
Faltan los recursos de la carpeta drawable

### ISSUE THREAD

**Issue by josmarpav** [tonilopezmr/Curso-Testing-on-Android#3]
Faltan varios recursos de la carpeta drawable que se hacen referencia desde algunos layouts y desde el código de algunas actividades. Ej: R.drawable.ic_done en BasicEspressoActivity.java.

**Comment by tonilopezmr** [comment]
Es cierto, voy a añadirlo en todas las ramas 👍

**Comment by tonilopezmr** [comment]
@josmarpav Ya está resuelto
